### ISSUE TITLE
Excluding routes

### ISSUE THREAD

**Issue by kiler129** [kiler129/SupercacheBundle#3]
In current version all routes gets cached if matches some criteria like HTTP code. Unfortunately there's no option to exclude resource from caching by route. The only option to do that is to set `no-store` or `private` caching property on response inside controller.

~~Proposition:~~

``` yaml
# This is NOT an final configuration - see comment below!
sandbox:
  path: /sandbox
  defaults: { _controller: 'SandboxBundle:Default:index'}
  options: { supercache: false }
```

**Comment by kiler129** [comment]
Configuration:

``` yaml
sandbox:
  path: /sandbox
  defaults: { _controller: 'SandboxBundle:Default:index', _supercache: false}
```

#### Why it changed exactly?

After research for good way to obtain `options` data I came across few notable obstacles. The very first one is Fabien [clearly stated](https://github.com/symfony/symfony/issues/11211#issuecomment-47450387) `options` is a rather internal part of route. Also searching further I found [while it can be done](https://github.com/symfony/symfony/issues/11171#issuecomment-46533737) that's gonna be slow and hacky.
It was [suggested and discussed](https://github.com/symfony/symfony-docs/issues/3960) `defaults` it's the right place to put route-specifiec settings.

#### So where `options` came from?

I used to use [JMSI18nRoutingBundle](https://github.com/schmittjoh/JMSI18nRoutingBundle) which utilize that part of configuration. However it's not a standard practice, but that was a valid usecase since `options` were intended for routes compilation and JMSI18nRoutingBundle afaik extends standard router.

**Comment by kiler129** [comment]
Side note: if you want to use `SupercacheBundle` in `dev` environment you should modify `app/routing_dev.yml`.
In standard installation it looks like that:

``` yaml
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error
```

Such configuration will cache profiler which was proven to produce strange results ;)
It's better to disable supercache for these routes;

``` yaml
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt
    defaults: { _supercache: false }

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler
    defaults: { _supercache: false }

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error
    defaults: { _supercache: false }
```
