### ISSUE TITLE
Route cache TTL / expiration

### ISSUE THREAD

**Issue by kiler129** [kiler129/SupercacheBundle#4]
All cache files live forever - they are served until deleted. Sometimes it will be useful to specify cache TTL.
Since matching by date and route inside `.htaccess` will be nightmare another method should be introduced.
This can be simple command executed by cron which checks all cached entries and it's expiration dates.

Proposition of configuration:

``` yaml
sandbox:
  path: /sandbox
  defaults: { _controller: 'SandboxBundle:Default:index'}
  options: { supercache.ttl: 24h }
```
