### ISSUE TITLE
Tagging / grouping caches

### ISSUE THREAD

**Issue by kiler129** [kiler129/SupercacheBundle#6]
Sometimes few routes directs to one physical object in the system. Example of such situation will be page with print-ready version and PDF.
Purging cache in such situation can be quite tricky - three entries need to be deleted manually. With tagging / grouping by route it will be possible to call e.g. `CacheManager::deleteEntriesByTag()` deleting all related entries.

Proposition of configuration:

``` yaml
sandboxPage:
  path: /sandbox
  defaults: { _controller: 'SandboxBundle:Default:index'}
  options: { supercache.tag: page }

sandboxPagePrint:
  path: /sandbox/print
  defaults: { _controller: 'SandboxBundle:Default:print'}
  options: { supercache.tag: page }

sandboxPagePdf:
  path: /sandbox.pdf
  defaults: { _controller: 'SandboxBundle:Default:pdf'}
  options: { supercache.tag: page }
```
