### ISSUE TITLE
Minification support

### ISSUE THREAD

**Issue by kiler129** [kiler129/SupercacheBundle#7]
In development mode it's useful to have well formatted HTML, even with comments. However it's waste of resources to transfer well formatted files with comments to user.
The idea is to introduce option to enable minification of HTML & JSON.

Configuration proposition:

``` yaml
supercache:
    optimizations:
        minifi_html: true
        minifi_js: true
```

Proposed configuration allow future extension (e.g. gzip, JS compression etc).
